### ISSUE TITLE
Setup CI integration

### ISSUE THREAD

**Issue by elbenfreund** [Dezentrale-eV/dezentrale_web#44]
@bocian67 do you feel comftable giving me admin rights to the repo so i can set up the CI or do you want to take care of this yourself?

**Comment by bocian67** [comment]
Where can I give the rights to you?

**Comment by elbenfreund** [comment]
The "navigation" that holds ``code``, ``issues``, ``insights``.. should also have a tab ``settings``.

**Comment by bocian67** [comment]
Yes, but where in settings is the option to give admin rights. Or do you mean transfer ownership?

**Comment by elbenfreund** [comment]
settings>collaborators & teams>create core team with admin rights>add me to the team :)

**Comment by elbenfreund** [comment]
ah... ya. its an 'organizations' thing...
I need to be afk right now. but will get back to you.

**Comment by bocian67** [comment]
@elbenfreund now you should be able since we are an organization

**Comment by elbenfreund** [comment]
Yes. Thanks
