### ISSUE TITLE
Update wagtail to 1.13

### ISSUE THREAD

**Issue by bocian67** [Dezentrale-eV/dezentrale_web#57]
No explanation required.
ref #59

**Comment by bocian67** [comment]
#59

**Comment by elbenfreund** [comment]
Well. Do we **need** any of the new features? :)
I would generally advise against following wagtails update cycle slavishly at this stage unless there is a reason to do so. The general dev environment should not change without good reason during the main devevlopment phase I think. Remember, each updates carries a risk of brakeking things too. ;)

**Comment by elbenfreund** [comment]
Also: please assign labels and milestones when creating issues :)
Also, you do not link PRs in the description. If the PR is done properly github will do this for you.

**Comment by bocian67** [comment]
It is important to keep things updated, since we want to develop a website for a local hackerspace, and we should keep it secure. In our develop-cycle we can test the things and decide if we want to upgrade.

**Comment by elbenfreund** [comment]
I was probably a bit unclear. Of cause we do not want to run outdated and stale software. :)
What I mean though was that we **develop** against a more or less fixed stack. We already got solutions in place to make sure that the deployed package will be kept up to date. We will deal with this once we are there :)
