### ISSUE TITLE
Update .gitignore

### ISSUE THREAD

**Issue by Rascat** [Dezentrale-eV/dezentrale_web#58]
There are two kinds of files that i think should be ignored and are not listed in .gitignore yet.
Those are:
- .idea/ (Probably only relevant for PyCharm users, but still...)
- *.sqlite

**Comment by elbenfreund** [comment]
Yes, But...! ;)

- ``idea`` is indeed some IDE artefact afaik. As such it should not be listed in the project specific ``.gitignore`` (that would mean that we maintain a list of all kinds of userspace swapfiles, which clearly is not viable) but instead should be ignored by the user him/herself. The most obvious place to do so is within the ``user gitignore`` commonly located at ``~/.gitignore``.
- ``sqlite``: yes. 👍
