### ISSUE TITLE
Agree on IRC-Channel

### ISSUE THREAD

**Issue by Rascat** [Dezentrale-eV/dezentrale_web#66]
When we last met IRL we decided that it would be handy sometimes to have some kind of chat to discuss certain issues in an informal way.
I would propose using the freenode channel #webdev.

Any thoughts?

**Comment by elbenfreund** [comment]
Maybe something less general :) Keep in mind that freenode is the goto network for FLOSS  projects. One would expect a channel named ``webdev`` to be a generic web dev meeting place.
How about ``dezentrale-dev`` or ``dezentrale-webdev``?

**Comment by bocian67** [comment]
Wouldn't it be a better solution to use Jabber?
I don't really know what would be easier, but IMHO jabber is really easy to use, free and saves the messages.

**Comment by elbenfreund** [comment]
yes. but my impression was that you two didn't like the idea. Personally I do think that a jabber MUC would be the way to go.

**Comment by bocian67** [comment]
Ok lets create an Jabber room, @Rascat has a jabber acc too now.
