### ISSUE TITLE
Minimal status of static website

### ISSUE THREAD

**Issue by bocian67** [Dezentrale-eV/dezentrale_web#68]
What should the Website include for the first static start?

## option 1
 it should include the LandingPage (Lokkes Template), the contact information in the footer and the official documents copied from our current wiki in pasted in the HTML.

## option 2
Maybe we can just show our LandingPage with the basic contact information and for now we could just integrate our current iwiki with links (to infrastructure, contact and documents). That would gives us more time to integrate these points correctly to our database and CMS (I don't know if that was technically correct but I think you know what I mean) and grants the Vorstand access as long as we are not finished.
What is your opinion on that?

**Comment by elbenfreund** [comment]
Thats for you to decide.

**Comment by bocian67** [comment]
I think that's something we all should decide, since it's our project.

**Comment by elbenfreund** [comment]
Well, the wiki has not tooo much infos anyway. so i would suggest static pages for:
- imprint (needed anyway)
- infrastructure
- official docs

I would Accountinformation  on the imprint page for now
All those static pages plus Mailinglists would get a ``section`` on the landing page with some short teaser text. Then each section provides a link to the static page with the content.

This should cover most relevant information. With regards to events, I would see what I can do tomorrow. there may be a first basic version using the existing events app.

**Comment by bocian67** [comment]
If I got it right, you want to make static pages for the three topics which are on the wiki right now. But I don't know if that would be a good option, since now some people have Access to the wiki and static pages could make Problems, don't you think?

**Comment by elbenfreund** [comment]
Yes. You will have to decide if you want static or dynamic content. If you want to keep it user editable *right now* then linking to the wiki is your only option as far as I can tell. If you want something consistent to show ppl on saturday, static pages are your only choice in that case. you will have to pick one unless I miss an alternative.

**Comment by bocian67** [comment]
Then I will now try to create some pages with the content c&p from the wiki.

**Comment by bocian67** [comment]
now we have our landingpage, 4 sites from the wiki (documents, infrastructure, girokonto, impressum). I also refreshed the hyperlinks that in the production environment all sites can be reached with their absolute link (started with domain, for example: https://dezentrale.space/dokumente). 
Tomorrow we should integrate it to the server, and if that fails we can send lokke a zipped file with the pages and assets and he will do it absolute static (as it is so far, but without django).

**Comment by bocian67** [comment]
Since we have a django project which fits the minimal status, I'll close this one.
