### ISSUE TITLE
Setup dependency monitoring

### ISSUE THREAD

**Issue by elbenfreund** [Dezentrale-eV/dezentrale_web#70]
I suggest we use one of the public services to parse and monitor our dependencies (as listed in ``/requirements`` and to notify us about relevant updates.
My service provide of choice so far has been requires.io. Unfortunately it seems only the actual repo owner can add the repo though. So if you want to go with them, @Rascat would have to set this up. It is rather straight forward, but if you need help I am happy to lend a hand.

**Comment by elbenfreund** [comment]
>n organization owner has approved the following application to access private data in the Dezentrale e.V. >organization:
>
 > "requires.io" from shiningpandaci

So someone is on this... any news/details?

**Comment by Rascat** [comment]
require does check our dependencies right now. Apparently, a lot of updating need to be done...

**Comment by elbenfreund** [comment]
hehe. yes. but the beauty is that requires will push a branch ready with a PR with all suggested changes ;)

**Comment by bocian67** [comment]
Monitoring is active, a repository badge needs to be added for a visible representation
