### ISSUE TITLE
Wiki discussion

### ISSUE THREAD

**Issue by bocian67** [Dezentrale-eV/dezentrale_web#73]
We have to decide what our wiki should contain, how we should build it and how it should work. 
I think the wiki should have an Author, Content and Heading just like the blogs. The Wiki should have an Index Page with search function, and tags (like "Audio") are possible. 
What are your opinions?

**Comment by elbenfreund** [comment]
I vaguely remember that we discussed this before. IIRC the result was that you wanted to *link to the existing wiki* right? If not, what exactly do you mean?

**Comment by elbenfreund** [comment]
Btw: I think *discussions* should be handled as such. I started on over [here](https://github.com/orgs/Dezentrale-eV/teams/website) copying your original post.
