### ISSUE TITLE
Deploy a first stable version to server

### ISSUE THREAD

**Issue by bocian67** [Dezentrale-eV/dezentrale_web#76]
I think we are as far as we can deploy our first version of the project. But we have still some work to do before we can deploy it! Django provides a checklist (https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/) which we should use. Some things that I have in mind to do: 

- submit #75 (done)
- add a Open/Closed status based on current on the website (started)
- work on Checklist (done)
- make a final beta test and deploy it finally (done)

on the Server itself change:
- set superuser (not needet RN)
- review host information (done?)
- test SSL information (working)

feel free to add points to make sure we do not forget anything.
I found this Documentation for deploying with WSGI: https://docs.djangoproject.com/en/2.0/howto/deployment/wsgi/

**Comment by stevenc99** [comment]
Done! https://dezentrale.space

No accounts or superuser is created yet.  Access to the /admin/ and other CMS pages is disabled at the moment, because the site is running with Debug=True

SSL seems to work well already.
